const jwt = require('jsonwebtoken');

const socketHandler = (io) => {

  // Authenticate every Socket.IO connection
  // using the same JWT generated by /api/auth/login.
  io.use((socket, next) => {
    try {
      let token = socket.handshake.auth?.token;

      if (
        typeof token !== 'string' ||
        !token.trim()
      ) {
        return next(
          new Error('Authentication token missing')
        );
      }

      token = token
        .replace(/^Bearer\s+/i, '')
        .trim();

      const decoded = jwt.verify(
        token,
        process.env.JWT_SECRET
      );

      if (!decoded?.userId) {
        return next(
          new Error('Invalid token payload')
        );
      }

      socket.user = decoded;

      next();

    } catch (error) {

      console.error(
        '❌ Socket authentication failed:',
        error.message
      );

      next(
        new Error('Invalid authentication token')
      );
    }
  });


  io.on('connection', (socket) => {

    console.log(
      `🔌 Socket connected: ${socket.id}`
    );

    const userId = socket.user.userId;

    // Server determines the private room
    // from the authenticated JWT.
    socket.join(`user_${userId}`);

    console.log(
      `👤 User ${userId} joined room user_${userId}`
    );


    socket.on('disconnect', (reason) => {

      console.log(
        `❌ Socket disconnected: ${socket.id} (${reason})`
      );

    });

  });
};


module.exports = {
  socketHandler,
};